### PR TITLE
Keyword and Symbol have `name` and `namespace` properties

### PR DESCRIPTION
**Pull request by bobby**
This small changes brings to parity with transit-ruby.

### CODE REVIEW

**Comment by ohpauleez** [comment]
Hey Bobby!  What's the motivation for this change - Is it in the Transit spec that Keywords and Symbols need to support namespaces?

**Comment by swannodette** [comment]
@ohpauleez the overall Transit spec doesn't specify (wisely) the nature of the instances that handlers construct. That's always been a platform specific concern. transit-js also supports name and namespace methods on Symbol and Keywords. It's a big simplification for a common need.

**Comment by bobby** [comment]
Yeah, I just ended up needing access to name and namespace in a python process, so I added it.

Cheers,
Bobby

**Comment by ohpauleez** [comment]
Ah cool, thanks guys!

**Comment by benkamphaus** [comment]
@bobby Thanks for the suggestion. We opted to implement a slightly different version of this change (now on master).

**Pull request closed without merging**
